[package]
name = "rml"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"
eframe = "0.27.2"
env_logger = "0.11.3"
mlua = { version = "0.9.8", features = ["lua54", "vendored"] }
